/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bear.api.type;  
@SuppressWarnings("all")
/** 表示实体对象的访问权限级别 */
@org.apache.avro.specific.AvroGenerated
public enum AccessScope { 
  ALL, USER, ROLE, TOKEN, SELF, SESSION  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AccessScope\",\"namespace\":\"org.bear.api.type\",\"doc\":\"表示实体对象的访问权限级别\",\"symbols\":[\"ALL\",\"USER\",\"ROLE\",\"TOKEN\",\"SELF\",\"SESSION\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
