/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bear.api.type;  
@SuppressWarnings("all")
/** 表示实体对象的状态 */
@org.apache.avro.specific.AvroGenerated
public enum Status { 
  ENABLED, DISABLED, DELETED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"Status\",\"namespace\":\"org.bear.api.type\",\"doc\":\"表示实体对象的状态\",\"symbols\":[\"ENABLED\",\"DISABLED\",\"DELETED\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
}
