package org.bear.identity.ex;

public interface ErrorCode extends org.bear.framework.ex.ErrorCode {
	/**
	 * 身份异常码
	 */
	static final int IDENTITY_ERROR = CUSTOM_ERROR_START * 3;

	static final int IDENTITY_USERNAME_OR_PWD_IS_NULL = IDENTITY_ERROR + 1;

	static final int IDENTITY_USERNAME_EXISTS = IDENTITY_ERROR + 2;

	static final int IDENTITY_EMAIL_IS_REQUIRED = IDENTITY_ERROR + 3;

	static final int IDENTITY_INCOMPLETED_REGISTRATION_INFO = IDENTITY_ERROR + 4;
	static final int IDENTITY_MAIL_EXISTS = IDENTITY_ERROR + 5;
	static final int IDENTITY_INVALID_USERNAME_OR_PASSWORD = IDENTITY_ERROR + 6;
	static final int IDENTITY_USER_NOT_EXIST = IDENTITY_ERROR + 7;
	static final int IDENTITY_USER_INCORRECT_RESULT_SIZE = IDENTITY_ERROR + 8;

	static final int IDENTITY_USERNAME_IS_REQUIRED = IDENTITY_ERROR + 9;
	static final int IDENTITY_PASSWORD_IS_REQUIRED = IDENTITY_ERROR + 10;

	static final int IDENTITY_ILLEGAL_ARGUMENTS = IDENTITY_ERROR + 11;

	static final int IDENTITY_INVALID_CREDENTIAL = IDENTITY_ERROR + 12;

	static final int IDENTITY_COULD_NOT_ACTIVATE_CREDENTIAL = IDENTITY_ERROR + 13;

	static final int IDENTITY_EXPIRED_CODE = IDENTITY_ERROR + 14;

	static final int IDENTITY_ILLEGAL_IDENTITY_STATUS = IDENTITY_ERROR + 15;

	static final int IDENTITY_INVALID_TOKEN = IDENTITY_ERROR + 16;

	static final int IDENTITY_RESET_PASSWORD_WITH_NO_EMAIL_MOBILE_CREDENTIALS = IDENTITY_ERROR + 17;

	static final int IDENTITY_INVALID_PASSWORD_PROTECTION = IDENTITY_ERROR + 18;

	static final int IDENTITY_INVALID_REGISTER_USER_INFO = IDENTITY_ERROR + 19;

	static final int IDENTITY_INVALID_USER_STATUS = IDENTITY_ERROR + 20;

	static final int IDENTITY_PASSWORD_PROTECTION_NOT_EXISTS = IDENTITY_ERROR + 21;

	static final int IDENTITY_NICKNAME_EXISTS = IDENTITY_ERROR + 22;

	static final int IDENTITY_INVALID_USER_INFO = IDENTITY_ERROR + 23;

	/**
	 * 属性异常码
	 */

	static final int ATTRIBUTE_ERROR = CUSTOM_ERROR_START * 4;

	static final int ATTRIBUTE_DEFINITION_IS_NULL = ATTRIBUTE_ERROR + 1;
	static final int ATTRIBUTE_DEFINITION_PHISICAL_NAME_IS_NULL = ATTRIBUTE_ERROR + 2;
	static final int ATTRIBUTE_DEFINITION_PHISICAL_NAME_DUPLICATED = ATTRIBUTE_ERROR + 3;
	static final int ATTRIBUTE_DEFINITION_NOT_EXISTS = ATTRIBUTE_ERROR + 4;
	static final int ATTRIBUTE_DEFINITION_INCORRECT_RESULT_SIZE = ATTRIBUTE_ERROR + 5;

	static final int ATTRIBUTE_DEFINITION_PHISICAL_NAME_NOT_EXISTS = ATTRIBUTE_ERROR + 6;

	/**
	 * 会话异常码
	 */
	static final int SESSION_ERROR = CUSTOM_ERROR_START * 5;
	static final int SESSION_INVALID_SESSION = SESSION_ERROR + 1;
	static final int SESSION_INVALID_TOKEN = SESSION_ERROR + 2;

	/**
	 * 凭证异常
	 */

	static final int CREDENTIAL_ERROR = CUSTOM_ERROR_START * 6;
	static final int CREDENTIAL_EXISTS = CREDENTIAL_ERROR + 1;
	static final int CREDENTIAL_INVALID = CREDENTIAL_ERROR + 2;
	static final int CREDENTIAL_NOT_EXISTS = CREDENTIAL_ERROR + 3;

	static final int CREDENTIAL_PROTECTION_NOT_EXISTS = CREDENTIAL_ERROR + 4;

	/**
	 * 用户组异常
	 */
	static final int GROUP_ERROR = CUSTOM_ERROR_START * 14;
	static final int GROUP_NAME_EXISTS = GROUP_ERROR + 1;
	static final int GROUP_NOT_EXISTS = GROUP_ERROR + 2;
	static final int GROUP_INVALID_GROUP = GROUP_ERROR + 3;
}
