/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bear.api.app;  
@SuppressWarnings("all")
/** * 表示一个业务配置 */
@org.apache.avro.specific.AvroGenerated
public class BizConfig extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"BizConfig\",\"namespace\":\"org.bear.api.app\",\"doc\":\"* 表示一个业务配置\",\"fields\":[{\"name\":\"bizId\",\"type\":\"int\",\"doc\":\"* 业务的编号\\r\\n\\t\\t *\\r\\n\\t\\t * @readonly\"},{\"name\":\"bizKey\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"* 业务的key\"},{\"name\":\"bizName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"* 业务的名称\"},{\"name\":\"configKey\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"* 配置key\\r\\n\\t\\t *\\r\\n\\t\\t * @readonly\"},{\"name\":\"configValue\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}],\"doc\":\"* 配置值\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  /** * 业务的编号
		 *
		 * @readonly */
  @Deprecated public int bizId;
  /** * 业务的key */
  @Deprecated public java.lang.String bizKey;
  /** * 业务的名称 */
  @Deprecated public java.lang.String bizName;
  /** * 配置key
		 *
		 * @readonly */
  @Deprecated public java.lang.String configKey;
  /** * 配置值 */
  @Deprecated public java.lang.String configValue;

  /**
   * Default constructor.
   */
  public BizConfig() {}

  /**
   * All-args constructor.
   */
  public BizConfig(java.lang.Integer bizId, java.lang.String bizKey, java.lang.String bizName, java.lang.String configKey, java.lang.String configValue) {
    this.bizId = bizId;
    this.bizKey = bizKey;
    this.bizName = bizName;
    this.configKey = configKey;
    this.configValue = configValue;
  }

  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return bizId;
    case 1: return bizKey;
    case 2: return bizName;
    case 3: return configKey;
    case 4: return configValue;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: bizId = (java.lang.Integer)value$; break;
    case 1: bizKey = (java.lang.String)value$; break;
    case 2: bizName = (java.lang.String)value$; break;
    case 3: configKey = (java.lang.String)value$; break;
    case 4: configValue = (java.lang.String)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }

  /**
   * Gets the value of the 'bizId' field.
   * * 业务的编号
		 *
		 * @readonly   */
  public java.lang.Integer getBizId() {
    return bizId;
  }

  /**
   * Sets the value of the 'bizId' field.
   * * 业务的编号
		 *
		 * @readonly   * @param value the value to set.
   */
  public void setBizId(java.lang.Integer value) {
    this.bizId = value;
  }

  /**
   * Gets the value of the 'bizKey' field.
   * * 业务的key   */
  public java.lang.String getBizKey() {
    return bizKey;
  }

  /**
   * Sets the value of the 'bizKey' field.
   * * 业务的key   * @param value the value to set.
   */
  public void setBizKey(java.lang.String value) {
    this.bizKey = value;
  }

  /**
   * Gets the value of the 'bizName' field.
   * * 业务的名称   */
  public java.lang.String getBizName() {
    return bizName;
  }

  /**
   * Sets the value of the 'bizName' field.
   * * 业务的名称   * @param value the value to set.
   */
  public void setBizName(java.lang.String value) {
    this.bizName = value;
  }

  /**
   * Gets the value of the 'configKey' field.
   * * 配置key
		 *
		 * @readonly   */
  public java.lang.String getConfigKey() {
    return configKey;
  }

  /**
   * Sets the value of the 'configKey' field.
   * * 配置key
		 *
		 * @readonly   * @param value the value to set.
   */
  public void setConfigKey(java.lang.String value) {
    this.configKey = value;
  }

  /**
   * Gets the value of the 'configValue' field.
   * * 配置值   */
  public java.lang.String getConfigValue() {
    return configValue;
  }

  /**
   * Sets the value of the 'configValue' field.
   * * 配置值   * @param value the value to set.
   */
  public void setConfigValue(java.lang.String value) {
    this.configValue = value;
  }

  /** Creates a new BizConfig RecordBuilder */
  public static org.bear.api.app.BizConfig.Builder newBuilder() {
    return new org.bear.api.app.BizConfig.Builder();
  }
  
  /** Creates a new BizConfig RecordBuilder by copying an existing Builder */
  public static org.bear.api.app.BizConfig.Builder newBuilder(org.bear.api.app.BizConfig.Builder other) {
    return new org.bear.api.app.BizConfig.Builder(other);
  }
  
  /** Creates a new BizConfig RecordBuilder by copying an existing BizConfig instance */
  public static org.bear.api.app.BizConfig.Builder newBuilder(org.bear.api.app.BizConfig other) {
    return new org.bear.api.app.BizConfig.Builder(other);
  }
  
  /**
   * RecordBuilder for BizConfig instances.
   */
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<BizConfig>
    implements org.apache.avro.data.RecordBuilder<BizConfig> {

    private int bizId;
    private java.lang.String bizKey;
    private java.lang.String bizName;
    private java.lang.String configKey;
    private java.lang.String configValue;

    /** Creates a new Builder */
    private Builder() {
      super(org.bear.api.app.BizConfig.SCHEMA$);
    }
    
    /** Creates a Builder by copying an existing Builder */
    private Builder(org.bear.api.app.BizConfig.Builder other) {
      super(other);
    }
    
    /** Creates a Builder by copying an existing BizConfig instance */
    private Builder(org.bear.api.app.BizConfig other) {
            super(org.bear.api.app.BizConfig.SCHEMA$);
      if (isValidValue(fields()[0], other.bizId)) {
        this.bizId = data().deepCopy(fields()[0].schema(), other.bizId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.bizKey)) {
        this.bizKey = data().deepCopy(fields()[1].schema(), other.bizKey);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.bizName)) {
        this.bizName = data().deepCopy(fields()[2].schema(), other.bizName);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.configKey)) {
        this.configKey = data().deepCopy(fields()[3].schema(), other.configKey);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.configValue)) {
        this.configValue = data().deepCopy(fields()[4].schema(), other.configValue);
        fieldSetFlags()[4] = true;
      }
    }

    /** Gets the value of the 'bizId' field */
    public java.lang.Integer getBizId() {
      return bizId;
    }
    
    /** Sets the value of the 'bizId' field */
    public org.bear.api.app.BizConfig.Builder setBizId(int value) {
      validate(fields()[0], value);
      this.bizId = value;
      fieldSetFlags()[0] = true;
      return this; 
    }
    
    /** Checks whether the 'bizId' field has been set */
    public boolean hasBizId() {
      return fieldSetFlags()[0];
    }
    
    /** Clears the value of the 'bizId' field */
    public org.bear.api.app.BizConfig.Builder clearBizId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /** Gets the value of the 'bizKey' field */
    public java.lang.String getBizKey() {
      return bizKey;
    }
    
    /** Sets the value of the 'bizKey' field */
    public org.bear.api.app.BizConfig.Builder setBizKey(java.lang.String value) {
      validate(fields()[1], value);
      this.bizKey = value;
      fieldSetFlags()[1] = true;
      return this; 
    }
    
    /** Checks whether the 'bizKey' field has been set */
    public boolean hasBizKey() {
      return fieldSetFlags()[1];
    }
    
    /** Clears the value of the 'bizKey' field */
    public org.bear.api.app.BizConfig.Builder clearBizKey() {
      bizKey = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /** Gets the value of the 'bizName' field */
    public java.lang.String getBizName() {
      return bizName;
    }
    
    /** Sets the value of the 'bizName' field */
    public org.bear.api.app.BizConfig.Builder setBizName(java.lang.String value) {
      validate(fields()[2], value);
      this.bizName = value;
      fieldSetFlags()[2] = true;
      return this; 
    }
    
    /** Checks whether the 'bizName' field has been set */
    public boolean hasBizName() {
      return fieldSetFlags()[2];
    }
    
    /** Clears the value of the 'bizName' field */
    public org.bear.api.app.BizConfig.Builder clearBizName() {
      bizName = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /** Gets the value of the 'configKey' field */
    public java.lang.String getConfigKey() {
      return configKey;
    }
    
    /** Sets the value of the 'configKey' field */
    public org.bear.api.app.BizConfig.Builder setConfigKey(java.lang.String value) {
      validate(fields()[3], value);
      this.configKey = value;
      fieldSetFlags()[3] = true;
      return this; 
    }
    
    /** Checks whether the 'configKey' field has been set */
    public boolean hasConfigKey() {
      return fieldSetFlags()[3];
    }
    
    /** Clears the value of the 'configKey' field */
    public org.bear.api.app.BizConfig.Builder clearConfigKey() {
      configKey = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /** Gets the value of the 'configValue' field */
    public java.lang.String getConfigValue() {
      return configValue;
    }
    
    /** Sets the value of the 'configValue' field */
    public org.bear.api.app.BizConfig.Builder setConfigValue(java.lang.String value) {
      validate(fields()[4], value);
      this.configValue = value;
      fieldSetFlags()[4] = true;
      return this; 
    }
    
    /** Checks whether the 'configValue' field has been set */
    public boolean hasConfigValue() {
      return fieldSetFlags()[4];
    }
    
    /** Clears the value of the 'configValue' field */
    public org.bear.api.app.BizConfig.Builder clearConfigValue() {
      configValue = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    @Override
    public BizConfig build() {
      try {
        BizConfig record = new BizConfig();
        record.bizId = fieldSetFlags()[0] ? this.bizId : (java.lang.Integer) defaultValue(fields()[0]);
        record.bizKey = fieldSetFlags()[1] ? this.bizKey : (java.lang.String) defaultValue(fields()[1]);
        record.bizName = fieldSetFlags()[2] ? this.bizName : (java.lang.String) defaultValue(fields()[2]);
        record.configKey = fieldSetFlags()[3] ? this.configKey : (java.lang.String) defaultValue(fields()[3]);
        record.configValue = fieldSetFlags()[4] ? this.configValue : (java.lang.String) defaultValue(fields()[4]);
        return record;
      } catch (Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }
}
