/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bear.api;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface SearcherService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SearcherService\",\"namespace\":\"org.bear.api\",\"types\":[{\"type\":\"record\",\"name\":\"Index\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]},{\"type\":\"record\",\"name\":\"Query\",\"fields\":[{\"name\":\"id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}}]}],\"messages\":{\"searcher\":{\"request\":[{\"name\":\"query\",\"type\":\"Query\"}],\"response\":\"null\"}}}");
  java.lang.Void searcher(org.bear.api.Query query) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends SearcherService {
    public static final org.apache.avro.Protocol PROTOCOL = org.bear.api.SearcherService.PROTOCOL;
    void searcher(org.bear.api.Query query, org.apache.avro.ipc.Callback<java.lang.Void> callback) throws java.io.IOException;
  }
}