/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bear.api.standard;  
@SuppressWarnings("all")
/** * 表示实体对象的访问权限级别
	 *
	 * @field ALL  所有人都可以访问
	 *
	 * @field USER 登陆用户即可访问
	 *
	 * @field ROLE 拥有指定角色才能访问
	 *
	 * @field TOKEN需要通过token认证才能访问
	 *
	 * @field SELF 只有自己才能访问
	 *
	 * @field SESSION 需要会话授权才能访问 */
@org.apache.avro.specific.AvroGenerated
public enum AccessScope { 
  ALL, USER, ROLE, TOKEN, SELF, SESSION  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"AccessScope\",\"namespace\":\"org.bear.api.standard\",\"doc\":\"* 表示实体对象的访问权限级别\\r\\n\\t *\\r\\n\\t * @field ALL  所有人都可以访问\\r\\n\\t *\\r\\n\\t * @field USER 登陆用户即可访问\\r\\n\\t *\\r\\n\\t * @field ROLE 拥有指定角色才能访问\\r\\n\\t *\\r\\n\\t * @field TOKEN需要通过token认证才能访问\\r\\n\\t *\\r\\n\\t * @field SELF 只有自己才能访问\\r\\n\\t *\\r\\n\\t * @field SESSION 需要会话授权才能访问\",\"symbols\":[\"ALL\",\"USER\",\"ROLE\",\"TOKEN\",\"SELF\",\"SESSION\"]}");
}
