/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bear.api.standard;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface StandardService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"StandardService\",\"namespace\":\"org.bear.api.standard\",\"types\":[],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends StandardService {
    public static final org.apache.avro.Protocol PROTOCOL = org.bear.api.standard.StandardService.PROTOCOL;
  }
}