/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bear.api.standard;

@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public interface StandardService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"StandardService\",\"namespace\":\"org.bear.api.standard\",\"types\":[{\"type\":\"enum\",\"name\":\"Gender\",\"symbols\":[\"UNKNOWN\",\"MALE\",\"FEMALE\"]},{\"type\":\"record\",\"name\":\"StackTrace\",\"doc\":\"* 异常堆栈对象\\r\\n\\t *\\r\\n\\t * @field className 发生异常的类\\r\\n\\t *\\r\\n\\t * @field methodName 发生异常的方法\\r\\n\\t *\\r\\n\\t * @field fileName 发生异常的文件\\r\\n\\t *\\r\\n\\t * @field lineNumber 发生异常的行号\",\"fields\":[{\"name\":\"className\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"methodName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"fileName\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"lineNumber\",\"type\":\"int\"}]},{\"type\":\"enum\",\"name\":\"AccessScope\",\"doc\":\"* 表示实体对象的访问权限级别\\r\\n\\t *\\r\\n\\t * @field ALL  所有人都可以访问\\r\\n\\t *\\r\\n\\t * @field USER 登陆用户即可访问\\r\\n\\t *\\r\\n\\t * @field ROLE 拥有指定角色才能访问\\r\\n\\t *\\r\\n\\t * @field TOKEN需要通过token认证才能访问\\r\\n\\t *\\r\\n\\t * @field SELF 只有自己才能访问\\r\\n\\t *\\r\\n\\t * @field SESSION 需要会话授权才能访问\",\"symbols\":[\"ALL\",\"USER\",\"ROLE\",\"TOKEN\",\"SELF\",\"SESSION\"]},{\"type\":\"error\",\"name\":\"GlobalException\",\"doc\":\"* 通用错误对象\\r\\n\\t *\\r\\n\\t * @field code 错误代码\\r\\n\\t *\\r\\n\\t * @field msg 错误消息\\r\\n\\t *\\r\\n\\t * @field stackTraces 错误堆栈，供调试用\",\"fields\":[{\"name\":\"code\",\"type\":\"int\"},{\"name\":\"msg\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"stackTraces\",\"type\":{\"type\":\"array\",\"items\":\"StackTrace\",\"java_class\":\"java.util.ArrayList\"}}]}],\"messages\":{}}");

  @SuppressWarnings("all")
  public interface Callback extends StandardService {
    public static final org.apache.avro.Protocol PROTOCOL = org.bear.api.standard.StandardService.PROTOCOL;
  }
}