/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bear.api.identity;  
@SuppressWarnings("all")
/** * 我的爱人名字？ */
@org.apache.avro.specific.AvroGenerated
public enum ProtectionQuestion { 
  FAV_FILM, FAV_MUSIC, FATHER_NAME, MOTHER_NAME, LOVER_NAME  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ProtectionQuestion\",\"namespace\":\"org.bear.api.identity\",\"doc\":\"* 我的爱人名字？\",\"symbols\":[\"FAV_FILM\",\"FAV_MUSIC\",\"FATHER_NAME\",\"MOTHER_NAME\",\"LOVER_NAME\"]}");
}
