/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package org.bear.api.identity;  
@SuppressWarnings("all")
@org.apache.avro.specific.AvroGenerated
public enum UserStatus { 
  INIT, NORMAL, DISABLED, ARCHIVED, LOCKED  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"UserStatus\",\"namespace\":\"org.bear.api.identity\",\"symbols\":[\"INIT\",\"NORMAL\",\"DISABLED\",\"ARCHIVED\",\"LOCKED\"]}");
}
